name: PR/Push Test-Error
on:
  pull_request:
    branches:
      - test-error
  push:
    branches:
      - test-error
  workflow_dispatch:
    inputs:
      early-exit:
        description: 'Early exit'
        type: boolean
        default: false
      exit-status:
        type: boolean
        default: false

jobs:
  skip_check:
    name: Skip check
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_duplicate.outputs.should_skip }}
    steps:
      - id: skip_duplicate
        uses: fkirc/skip-duplicate-actions@v5

  tests:
    name: Run test on ${{ matrix.name }}
    needs: [skip_check]
    if: needs.skip_check.outputs.should_skip != 'true'
    strategy:
      matrix:
        name: [sequencer-devnet, rpc-devnet]
        include:
          - name: sequencer-devnet
            TEST_PROVIDER_BASE_URL: http://127.0.0.1:5050/
          - name: rpc-devnet
            TEST_RPC_URL: http://127.0.0.1:5050/rpc

    uses: ./.github/workflows/_test.yml
    secrets:
      TEST_PROVIDER_BASE_URL: ${{ matrix.TEST_PROVIDER_BASE_URL }}
      TEST_RPC_URL: ${{ matrix.TEST_RPC_URL }}

  release:
    name: Release
    needs: [skip_check, tests]
    if: |
      !cancelled() && !failure()
      && needs.skip_check.outputs.should_skip != ''
      && github.event_name == 'push'
    uses: ./.github/workflows/_release.yml
    secrets: inherit
